json.id program.id
json.name program.name
json.description program.description
json.donation_goal program.donation_goal
json.total_donated program.total_donated
json.start_date program.start_date
json.end_date program.end_date
json.address program.address
json.zipcode program.zipcode
json.city program.city
json.latitude program.latitude
json.longitude program.longitude
json.visits program.visits
json.photo program.photo
